### ISSUE TITLE
CSV Dialect

### ISSUE THREAD

**Issue by andrejjh** [frictionlessdata/FrictionlessDarwinCore#1]
Tool needs to set CSV dialect for all tabular-data-resource. 
Most information(eg encoding, fieldDelimiter, lineDelimiter, header) to be retrieved from DwC meta.xml.

**Comment by niconoe** [comment]
You may use the `DataFileDescriptor` / `ArchiveDescriptor` classes from python-dwca-reader to get extract that info from meta.xml (or try to autodetect stuff if there's no meta.xml).

For your specific use case, I don't know if it's easier to rely on it or directly read values from the xml file. In that case you can also look at the implementation of those classes to gain some time.

**Comment by roll** [comment]
Hi @andrejjh, sorry for the delay with the answer

Could you please provide some example data and schema so I can reproduce this error with goodtables?

**Comment by andrejjh** [comment]
Hi @roll,
Here is an example zipped data package that shows the error [-,-] [source-error] field larger than field limit (131072)
One data field of line 102 in occurrence.txt has single ".
That's why I want support of QUOTING_NONE in CSV dialect.

[C1dp.zip](https://github.com/frictionlessdata/FrictionlessDarwinCore/files/3609169/C1dp.zip)

**Comment by roll** [comment]
Hi @andrejjh,

Please try to set `qutochar=""` with:

```
pip install --upgrade tabulator@1.24.3
```

**Comment by andrejjh** [comment]
Hi @roll,

I guess it's quotechar="" not qutochar="" but I got this error:

````
pip install --upgrade tabulator@1.24.3
ERROR: Invalid requirement: 'tabulator@1.24.3'
```

**Comment by roll** [comment]
@andrejjh 
Sorry for the inaccuracy:

- `"quoteChar": "",`
- `pip install --upgrade tabulator==1.24.3` (the `@` is for JavaScript=)

**Comment by andrejjh** [comment]
@roll 
Excellent, "quoteChar":"" with tabulator 1.24.3 solves my 'quoting none' problem and goodtables now accept the suspicious data resource as is.
