### ISSUE TITLE
Question: does the tool support arbitrary Darwin Core terms / column names?

### ISSUE THREAD

**Issue by niconoe** [frictionlessdata/FrictionlessDarwinCore#4]
I noticed the CSV file with column name, types, ...

I understand the usefulness of having types and restrictions on columns, but given the variability of the DwC-A "in the wild" and the difficulty to know exactly what's part of each standard, I think it would be good if the tool also support arbitrary columns (assign them the type string).

(maybe that's already the case, didn't checked...)

**Comment by andrejjh** [comment]
That's indeed already the case. Terms not present in the DwCVocabulary table are treated with 'string' type.
