### ISSUE TITLE
Improvement: make sure the conversion can requested from Python code, without using the "fdwca" executable

### ISSUE THREAD

**Issue by niconoe** [frictionlessdata/FrictionlessDarwinCore#6]
I suspect we're not far from it, probably still needs a few things such as:

- an example in the documentation
- report errors and warning without using print() in the middle of conversion methods

**Comment by andrejjh** [comment]
Indeed, Python conversion code currently looks like this:
````
        da = DwCArchive(dwca)
        da.infer()
        if da.valid():
            da.save(outpath)
````

**Comment by andrejjh** [comment]
Python use chapter added to README.md with basic code that shows how to create and save a DwCArchive object.
