### ISSUE TITLE
Initial review

### ISSUE THREAD

**Issue by roll** [frictionlessdata/FrictionlessDarwinCore#7]
# Review

It's great work! Congratulations!

My comments will be related mostly to organizational things and some minor codebase details.

## Codebase

A few notes regarding the functionality:

- it allows saving a zip archive, a descriptor, and a readme. I would consider also adding a method to save the data itself.
- it seems there is a typo in the readme `if da.valid(): -> if da.valid:`

## Maintainance

Here are my recommendations regarding the repository:

- renaming the repo and the lib to something like `datapackage-dwca/darwin/etc` to be aligned with our naming conventions
- following the [oki-py](https://github.com/okfn/oki-py) repo structure regarding files like Makefile etc. Maybe the more up-to-date example is [datapacakge-py](https://github.com/frictionlessdata/datapackage-py). Using this approach ensures that all community members are able to work with the repo using familiar commands like `make test` , established releasing technics, etc
- setting up TravisCI and Coveralls for continuous testing and releasing (I've enabled them for the repo). So the missing parts are `travis.yml`, readme's badges, etc
- releasing the repo to PyPi following the SemVer versioning approach

PS.
It's a long shot but I'm curious whether it can support the `Storage API` also (maybe in the future):
- https://github.com/frictionlessdata/tableschema-py#storage
- https://github.com/frictionlessdata/tableschema-sql-py (for example)

cc @lwinfree @andrejjh

**Comment by andrejjh** [comment]
CLI now accepts -f csv optional parameter to save the data file(s) apart in a zip file.
