### ISSUE TITLE
Support for Darwin Core archives with default values

### ISSUE THREAD

**Issue by niconoe** [frictionlessdata/FrictionlessDarwinCore#9]
In a Darwin Core archive, you can specify in the metafile a default value for a given field, with something such as `<field term="http://rs.tdwg.org/dwc/terms/datasetID" default="urn:lsid:tim.lsid.tdwg.org:collections:1"/>`

I tried to convert an [Archive making use of this feature](https://github.com/BelgianBiodiversityPlatform/python-dwca-reader/blob/master/dwca/test/sample_files/dwca-test-default.zip), but it doesn't seem supported (I don't see any default value in `datapackage.json`, and according to goodtables the columns and headers seems misaligned).

Notes:

- The IPT makes use of this feature if you select a default value for a field (or at least, it dit at some point in the past).
- I just learned on https://dwc.tdwg.org/text/ that you can specify a column AND a default value for a given field (in that case, the default is only used when the cell is empty), that's probably another subcase to handle.

**Comment by andrejjh** [comment]
As frictionless table schema does not support default values, 1)DwC files with default values will have to be transformed in order to hold these default values for specified columns. OR 2)table schema specifications have to be adapted to include default values.
I'll try to add such transformations (1) when necessary.

**Comment by andrejjh** [comment]
Added data transformation to cope with DwC default values, adding CSV column when needed.Specific case, with default value and column (second bullet point mentioned by Nico), not handled yet.
